export const LOGOUT = 'LOGOUT';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SUCCESS_CURRENT_USER = 'SUCCESS_CURRENT_USER';
export const FAILED_CURRENT_USER = 'FAILED_CURRENT_USER';

export const SET_TITLE = 'SET_TITLE';

export const SEARCH_TRACKS ='SEARCH_TRACKS';
export const SUCCESS_SEARCH_TRACKS = 'SUCCESS_SEARCH_TRACKS';
export const CLEAR_SEARCH_RES = 'CLEAR_SEARCH_RES';

export const GET_CURRENT_TRACK = 'GET_CURRENT_TRACK';
export const SUCCESS_CURRENT_TRACK = 'SUCCESS_CURRENT_TRACK';

export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const SUCCESS_GET_PLAYLISTS = 'SUCCESS_GET_PLAYLISTS';
export const CLEAR_PLAYLISTS = 'CLEAR_PLAYLISTS';

export const GET_PLAYLIST_TRACKS = 'GET_PLAYLIST_TRACKS';
export const SUCCESS_PLAYLIST_TRACKS = 'SUCCESS_PLAYLIST_TRACKS';
export const CLEAR_PLAYLIST_TRACKS = 'CLEAR_PLAYLIST_TRACKS';

export const SET_PREVIEW_TRACK = 'SET_PREVIEW_TRACK';
export const CLEAR_PREVIEW_TRACK = 'CLEAR_PREVIEW_TRACK';

export const SET_PREVIOUS_TRACK = 'SET_PREVIOUS_TRACK';
export const SET_NEXT_TRACK = 'SET_NEXT_TRACK';

export const PAUSE_GLOBAL_TRACK = 'PAUSE_GLOBAL_TRACK';
export const PLAY_GLOBAL_TRACK = 'PLAY_GLOBAL_TRACK';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const ADD_ERROR = 'ADD_ERROR';
